"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import StudentSidebar from "@/components/dashboard/StudentSidebar";
import { api, API_BASE_URL } from "@/lib/api";

interface Profile { userId: string; companyName: string; licenseNumber: string | null; website: string | null; address: string | null; description: string | null; isVerified: boolean; certificates: { id: string; title: string; fileName: string; expiresAt: string | null }[]; }
export default function AgencyPublicProfilePage() {
  const params = useParams<{ id: string }>(); const [agency, setAgency] = useState<Profile | null>(null);
  useEffect(() => { if (params.id) api.get<Profile>(`/api/agency/${params.id}/public`, { auth: false }).then(setAgency).catch(() => setAgency(null)); }, [params.id]);
  return <><StudentSidebar /><main className="md:ml-[260px] min-h-screen bg-background p-6 md:p-10"><div className="max-w-4xl mx-auto"><Link href="/student/agencies" className="text-primary font-semibold text-sm">← All agencies</Link>{!agency ? <p className="mt-10 text-on-surface-variant">Loading agency profile…</p> : <><section className="ambient-card bg-surface-container-lowest rounded-3xl p-8 mt-6"><div className="flex gap-5 items-start"><div className="w-16 h-16 shrink-0 bg-primary-container rounded-2xl text-primary flex items-center justify-center"><span className="material-symbols-outlined text-3xl">business</span></div><div><div className="flex flex-wrap gap-3 items-center"><h1 className="font-headline-lg text-primary">{agency.companyName}</h1>{agency.isVerified && <span className="text-xs font-bold bg-secondary-fixed text-primary px-3 py-1 rounded-full">Verified agency</span>}</div>{agency.address && <p className="text-on-surface-variant mt-2">{agency.address}</p>}</div></div><p className="text-on-surface-variant mt-7 leading-7">{agency.description || "This agency has not added a description yet."}</p>{agency.website && <a className="inline-flex mt-5 text-primary font-bold" href={agency.website} target="_blank" rel="noreferrer">Visit website ↗</a>}</section><section className="ambient-card bg-surface-container-lowest rounded-3xl p-8 mt-6"><h2 className="font-headline-sm text-on-surface">Certificates & credentials</h2><p className="text-on-surface-variant mt-2">Documents uploaded by this agency for students to review.</p><div className="mt-6 space-y-3">{agency.certificates.length === 0 ? <p className="text-on-surface-variant">No certificates uploaded yet.</p> : agency.certificates.map((certificate) => <div key={certificate.id} className="flex justify-between items-center gap-3 bg-surface-container-low rounded-xl p-4"><div className="flex gap-3 items-center min-w-0"><span className="material-symbols-outlined text-primary">workspace_premium</span><div><p className="font-bold truncate">{certificate.title}</p><p className="text-sm text-on-surface-variant">{certificate.fileName}</p></div></div><a href={`${API_BASE_URL}/api/agency/files/${certificate.id}/file`} target="_blank" rel="noreferrer" className="text-primary font-bold text-sm">View</a></div>)}</div></section></>}</div></main></>;
}
